apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: coffee-virtual-server
  labels:
    f5cr: "true"
  namespace: default
spec:
  host: coffee.example.com
  ipamLabel: Production
  tlsProfileName: reencrypt-tls
  pools:
    - path: /coffee
      service: nginx-service
      servicePort: 8080
