apiVersion: "cis.f5.com/v1"
kind: ExternalDNS
metadata:
  name: exdns
  labels:
    f5cr: "true"
spec:
  domainName: gtm2.f5demo.com
  dnsRecordType: A
  loadBalanceMethod: round-robin
  pools:
  - name: gtm-pool-gtm2.f5demo.com
    dnsRecordType: A
    loadBalanceMethod: round-robin
    dataServerName: /Common/GSLBServer
